"""complete product modules

Revision ID: 04d65e1a9410
Revises: 53c727ba73aa
Create Date: 2026-08-04 15:01:45.087986
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '04d65e1a9410'
down_revision: Union[str, Sequence[str], None] = '53c727ba73aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_app_settings_key'))
    )
    op.create_table('connector_definitions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_connector_definitions_code'))
    )
    op.create_table('import_batches',
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_table('asset_attachments',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_attachments_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_attachments'))
    )
    op.create_table('asset_events',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_events_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_events'))
    )
    op.create_index('ix_asset_events_asset', 'asset_events', ['asset_id', 'occurred_at'], unique=False)
    op.create_table('device_profiles',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('assignee_person_id', sa.Uuid(), nullable=True),
    sa.Column('warranty_expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_device_profiles_asset_id_assets')),
    sa.ForeignKeyConstraint(['assignee_person_id'], ['people.id'], name=op.f('fk_device_profiles_assignee_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_profiles')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_device_profiles_asset_id'))
    )
    op.create_table('domain_profiles',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('domain_name', sa.String(length=253), nullable=False),
    sa.Column('registrar', sa.String(length=200), nullable=True),
    sa.Column('dns_provider', sa.String(length=200), nullable=True),
    sa.Column('certificate_provider', sa.String(length=200), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_domain_profiles_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_profiles')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_domain_profiles_asset_id')),
    sa.UniqueConstraint('domain_name', name=op.f('uq_domain_profiles_domain_name'))
    )
    op.create_table('handovers',
    sa.Column('handover_no', sa.String(length=50), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_person_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_person_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_handovers_person_id_people')),
    sa.ForeignKeyConstraint(['receiver_person_id'], ['people.id'], name=op.f('fk_handovers_receiver_person_id_people')),
    sa.ForeignKeyConstraint(['reviewer_person_id'], ['people.id'], name=op.f('fk_handovers_reviewer_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handovers')),
    sa.UniqueConstraint('handover_no', name=op.f('uq_handovers_handover_no'))
    )
    op.create_table('infrastructure_profiles',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('external_resource_id', sa.String(length=300), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('public_address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_infrastructure_profiles_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infrastructure_profiles')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_infrastructure_profiles_asset_id'))
    )
    op.create_table('risk_findings',
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_risk_findings_asset_id_assets')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_risk_findings_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_findings'))
    )
    op.create_table('workflow_requests',
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requester_person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_workflow_requests_asset_id_assets')),
    sa.ForeignKeyConstraint(['requester_person_id'], ['people.id'], name=op.f('fk_workflow_requests_requester_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_requests')),
    sa.UniqueConstraint('request_no', name=op.f('uq_workflow_requests_request_no'))
    )
    op.create_table('provider_connections',
    sa.Column('connector_definition_id', sa.Uuid(), nullable=False),
    sa.Column('legal_entity_id', sa.Uuid(), nullable=False),
    sa.Column('platform_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('credential_reference_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_definition_id'], ['connector_definitions.id'], name=op.f('fk_provider_connections_connector_definition_id_connector_definitions')),
    sa.ForeignKeyConstraint(['credential_reference_id'], ['credential_references.id'], name=op.f('fk_provider_connections_credential_reference_id_credential_references')),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], name=op.f('fk_provider_connections_legal_entity_id_legal_entities')),
    sa.ForeignKeyConstraint(['platform_tenant_id'], ['platform_tenants.id'], name=op.f('fk_provider_connections_platform_tenant_id_platform_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_connections'))
    )
    op.create_table('external_mappings',
    sa.Column('provider_connection_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('external_type', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('external_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_external_mappings_asset_id_assets')),
    sa.ForeignKeyConstraint(['provider_connection_id'], ['provider_connections.id'], name=op.f('fk_external_mappings_provider_connection_id_provider_connections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_mappings')),
    sa.UniqueConstraint('provider_connection_id', 'external_type', 'external_id', name=op.f('uq_external_mappings_provider_connection_id'))
    )
    op.create_table('sync_jobs',
    sa.Column('provider_connection_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_connection_id'], ['provider_connections.id'], name=op.f('fk_sync_jobs_provider_connection_id_provider_connections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_jobs'))
    )
    op.create_table('sync_job_runs',
    sa.Column('sync_job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], name=op.f('fk_sync_job_runs_sync_job_id_sync_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_job_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_job_runs')
    op.drop_table('sync_jobs')
    op.drop_table('external_mappings')
    op.drop_table('provider_connections')
    op.drop_table('workflow_requests')
    op.drop_table('risk_findings')
    op.drop_table('infrastructure_profiles')
    op.drop_table('handovers')
    op.drop_table('domain_profiles')
    op.drop_table('device_profiles')
    op.drop_index('ix_asset_events_asset', table_name='asset_events')
    op.drop_table('asset_events')
    op.drop_table('asset_attachments')
    op.drop_table('import_batches')
    op.drop_table('connector_definitions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###

