"""initial asset ledger schema

Revision ID: 53c727ba73aa
Revises:
Create Date: 2026-08-04 13:21:23.294901
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "53c727ba73aa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_categories",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["asset_categories.id"],
            name=op.f("fk_asset_categories_parent_id_asset_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_asset_categories_code")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("object_type", sa.String(length=80), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_object",
        "audit_logs",
        ["object_type", "object_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "legal_entities",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entities")),
        sa.UniqueConstraint("code", name=op.f("uq_legal_entities_code")),
    )
    op.create_table(
        "metric_definitions",
        sa.Column("metric_key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("aggregation", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_definitions")),
        sa.UniqueConstraint("metric_key", name=op.f("uq_metric_definitions_metric_key")),
    )
    op.create_table(
        "providers",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("code", name=op.f("uq_providers_code")),
    )
    op.create_table(
        "asset_types",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("profile_kind", sa.String(length=80), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("completeness_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["asset_categories.id"],
            name=op.f("fk_asset_types_category_id_asset_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_types")),
        sa.UniqueConstraint("category_id", "code", name=op.f("uq_asset_types_category_id")),
    )
    op.create_table(
        "departments",
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_departments_legal_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["departments.id"], name=op.f("fk_departments_parent_id_departments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("legal_entity_id", "code", name=op.f("uq_departments_legal_entity_id")),
    )
    op.create_table(
        "platforms",
        sa.Column("provider_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.id"], name=op.f("fk_platforms_provider_id_providers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platforms")),
        sa.UniqueConstraint("provider_id", "code", name=op.f("uq_platforms_provider_id")),
    )
    op.create_table(
        "service_products",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("service_category", sa.String(length=80), nullable=False),
        sa.Column("billing_mode", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_service_products_provider_id_providers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_products")),
        sa.UniqueConstraint("provider_id", "code", name=op.f("uq_service_products_provider_id")),
    )
    op.create_table(
        "asset_field_definitions",
        sa.Column("asset_type_id", sa.Uuid(), nullable=False),
        sa.Column("field_key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("data_type", sa.String(length=32), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_types.id"],
            name=op.f("fk_asset_field_definitions_asset_type_id_asset_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_field_definitions")),
        sa.UniqueConstraint(
            "asset_type_id", "field_key", name=op.f("uq_asset_field_definitions_asset_type_id")
        ),
    )
    op.create_table(
        "assets",
        sa.Column("asset_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type_id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("owner_department_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("confidentiality", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_type_id"], ["asset_types.id"], name=op.f("fk_assets_asset_type_id_asset_types")
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_assets_legal_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_department_id"],
            ["departments.id"],
            name=op.f("fk_assets_owner_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint(
            "legal_entity_id", "asset_code", name=op.f("uq_assets_legal_entity_id")
        ),
    )
    op.create_index(
        "ix_assets_scope",
        "assets",
        ["legal_entity_id", "owner_department_id", "asset_type_id"],
        unique=False,
    )
    op.create_index("ix_assets_status", "assets", ["status", "criticality"], unique=False)
    op.create_table(
        "people",
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("employee_no", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("employment_status", sa.String(length=32), nullable=False),
        sa.Column("person_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("fk_people_department_id_departments")
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_people_legal_entity_id_legal_entities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        sa.UniqueConstraint(
            "legal_entity_id", "employee_no", name=op.f("uq_people_legal_entity_id")
        ),
    )
    op.create_table(
        "asset_field_values",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("field_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_asset_field_values_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["field_definition_id"],
            ["asset_field_definitions.id"],
            name=op.f("fk_asset_field_values_field_definition_id_asset_field_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_field_values")),
        sa.UniqueConstraint(
            "asset_id", "field_definition_id", name=op.f("uq_asset_field_values_asset_id")
        ),
    )
    op.create_table(
        "asset_relations",
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("target_asset_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_asset_id <> target_asset_id", name=op.f("ck_asset_relations_different_assets")
        ),
        sa.ForeignKeyConstraint(
            ["source_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_relations_source_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["target_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_relations_target_asset_id_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_relations")),
        sa.UniqueConstraint(
            "source_asset_id",
            "target_asset_id",
            "relation_type",
            name=op.f("uq_asset_relations_source_asset_id"),
        ),
    )
    op.create_table(
        "asset_responsibilities",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("role_type", sa.String(length=50), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=True),
        sa.Column("ends_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(person_id IS NOT NULL AND department_id IS NULL) OR "
            "(person_id IS NULL AND department_id IS NOT NULL)",
            name=op.f("ck_asset_responsibilities_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_asset_responsibilities_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_asset_responsibilities_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_asset_responsibilities_person_id_people")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_responsibilities")),
    )
    op.create_index(
        "ix_asset_responsibilities_subject",
        "asset_responsibilities",
        ["person_id", "department_id", "role_type"],
        unique=False,
    )
    op.create_table(
        "internal_system_profiles",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("repository_url", sa.String(length=1000), nullable=True),
        sa.Column("production_url", sa.String(length=1000), nullable=True),
        sa.Column("tech_stack", sa.Text(), nullable=True),
        sa.Column("deployment_guide_url", sa.String(length=1000), nullable=True),
        sa.Column("recovery_guide_url", sa.String(length=1000), nullable=True),
        sa.Column("backup_description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_internal_system_profiles_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_internal_system_profiles")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_internal_system_profiles_asset_id")),
    )
    op.create_table(
        "platform_tenants",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("platform_id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_identifier", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_platform_tenants_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_platform_tenants_legal_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
            name=op.f("fk_platform_tenants_platform_id_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_tenants")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_platform_tenants_asset_id")),
        sa.UniqueConstraint(
            "platform_id",
            "legal_entity_id",
            "tenant_identifier",
            name=op.f("uq_platform_tenants_platform_id"),
        ),
    )
    op.create_table(
        "service_instances",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("service_product_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_platform_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_tenant_asset_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_name", sa.String(length=200), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_service_instances_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["purchase_platform_id"],
            ["platforms.id"],
            name=op.f("fk_service_instances_purchase_platform_id_platforms"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_tenant_asset_id"],
            ["assets.id"],
            name=op.f("fk_service_instances_purchase_tenant_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["service_product_id"],
            ["service_products.id"],
            name=op.f("fk_service_instances_service_product_id_service_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_instances")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_service_instances_asset_id")),
    )
    op.create_table(
        "accounts",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("platform_tenant_id", sa.Uuid(), nullable=False),
        sa.Column("login_identifier", sa.String(length=320), nullable=False),
        sa.Column("normalized_login_identifier", sa.String(length=320), nullable=False),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("registration_identity_type", sa.String(length=50), nullable=False),
        sa.Column("registration_person_id", sa.Uuid(), nullable=True),
        sa.Column("mfa_status", sa.String(length=32), nullable=False),
        sa.Column("privilege_level", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_accounts_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["platform_tenant_id"],
            ["platform_tenants.id"],
            name=op.f("fk_accounts_platform_tenant_id_platform_tenants"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_person_id"],
            ["people.id"],
            name=op.f("fk_accounts_registration_person_id_people"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_accounts_asset_id")),
        sa.UniqueConstraint(
            "platform_tenant_id",
            "normalized_login_identifier",
            name=op.f("uq_accounts_platform_tenant_id"),
        ),
    )
    op.create_table(
        "metric_samples",
        sa.Column("service_instance_id", sa.Uuid(), nullable=False),
        sa.Column("metric_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.id"],
            name=op.f("fk_metric_samples_metric_definition_id_metric_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["service_instance_id"],
            ["service_instances.id"],
            name=op.f("fk_metric_samples_service_instance_id_service_instances"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_samples")),
    )
    op.create_index(
        "ix_metric_samples_lookup",
        "metric_samples",
        ["service_instance_id", "metric_definition_id", "collected_at"],
        unique=False,
    )
    op.create_table(
        "account_grants",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("privilege_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=True),
        sa.Column("ends_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_account_grants_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_account_grants_person_id_people")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_grants")),
        sa.UniqueConstraint(
            "account_id",
            "person_id",
            "privilege_level",
            "starts_at",
            name=op.f("uq_account_grants_account_id"),
        ),
    )
    op.create_table(
        "credential_references",
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("item_id", sa.String(length=500), nullable=False),
        sa.Column("secure_url", sa.String(length=1000), nullable=True),
        sa.Column("last_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_credential_references_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_credential_references_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credential_references")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credential_references")
    op.drop_table("account_grants")
    op.drop_index("ix_metric_samples_lookup", table_name="metric_samples")
    op.drop_table("metric_samples")
    op.drop_table("accounts")
    op.drop_table("service_instances")
    op.drop_table("platform_tenants")
    op.drop_table("internal_system_profiles")
    op.drop_index("ix_asset_responsibilities_subject", table_name="asset_responsibilities")
    op.drop_table("asset_responsibilities")
    op.drop_table("asset_relations")
    op.drop_table("asset_field_values")
    op.drop_table("people")
    op.drop_index("ix_assets_status", table_name="assets")
    op.drop_index("ix_assets_scope", table_name="assets")
    op.drop_table("assets")
    op.drop_table("asset_field_definitions")
    op.drop_table("service_products")
    op.drop_table("platforms")
    op.drop_table("departments")
    op.drop_table("asset_types")
    op.drop_table("providers")
    op.drop_table("metric_definitions")
    op.drop_table("legal_entities")
    op.drop_index("ix_audit_logs_object", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("asset_categories")
    # ### end Alembic commands ###
