<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ArrowLeft, CircleDollarSign, Gauge, Play, Plus, RefreshCw } from "lucide-vue-next";
import { useRoute } from "vue-router";

import ModalPanel from "../components/ModalPanel.vue";
import PageHeader from "../components/PageHeader.vue";
import StatusBadge from "../components/StatusBadge.vue";
import { api, type LegalEntity, type ServiceInstance, type UsageConnection } from "../lib/api";

type PlatformCode = "deepseek" | "minimax" | "aliyun";
const route = useRoute();
const platformCode = computed<PlatformCode>(() => {
  const code = route.params.platformCode;
  return code === "minimax" || code === "aliyun" ? code : "deepseek";
});
const isDeepSeek = computed(() => platformCode.value === "deepseek");
const isMiniMax = computed(() => platformCode.value === "minimax");
const isAliyun = computed(() => platformCode.value === "aliyun");
const platformMeta = computed(() => isDeepSeek.value
  ? { title: "DeepSeek 账户余额", description: "官方 API 仅提供开放平台账号当前余额；不支持查询各 API Key 历史用量。", connect: "连接账户", credential: "账户 API 访问凭证（Bearer Key）" }
  : isMiniMax.value
    ? { title: "MiniMax Token Plan 额度", description: "官方接口通过 Token Plan 订阅 Key 查询套餐、额度、积分和用量状态；普通按量 API Key 不在此模块内。", connect: "连接 Token Plan", credential: "Token Plan 订阅 Key" }
    : { title: "阿里云账户余额", description: "BSS OpenAPI 可查询阿里云账号当前可用额度、现金余额与信控余额。", connect: "连接阿里云账户", credential: "RAM AccessKey" });
const connections = ref<UsageConnection[]>([]); const entities = ref<LegalEntity[]>([]); const instances = ref<ServiceInstance[]>([]); const loading = ref(true); const saving = ref(false); const workingId = ref(""); const error = ref(""); const notice = ref(""); const modal = ref(false);
const form = reactive({ legal_entity_id: "", service_instance_id: "", name: "", api_key: "", access_key_id: "", access_key_secret: "" });
const entityName = computed(() => Object.fromEntries(entities.value.map((item) => [item.id, item.name])));
const instanceName = computed(() => Object.fromEntries(instances.value.map((item) => [item.id, item.subscription_name || `服务实例 ${item.id.slice(0, 8)}`])));
const platformConnections = computed(() => connections.value.filter((item) => item.platform_code === platformCode.value));
function config(item: UsageConnection, key: string): string { const value = item.configuration[key]; return value === null || value === undefined || value === "" ? "未设置" : String(value); }
function snapshot(item: UsageConnection): Record<string, unknown> { const value = item.configuration.latest_snapshot; return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function balances(item: UsageConnection): Record<string, string>[] { const values = snapshot(item).balances; return Array.isArray(values) ? values.filter((row): row is Record<string, string> => !!row && typeof row === "object") : []; }
function miniMaxItems(item: UsageConnection): Record<string, string>[] { const values = snapshot(item).items; return Array.isArray(values) ? values.filter((row): row is Record<string, string> => !!row && typeof row === "object") : []; }
function balanceLabel(balance: Record<string, string>): string { return balance.label || `${balance.currency || "账户"} 当前可用余额`; }
function balanceValue(balance: Record<string, string>): string { return balance.value || balance.total_balance || "—"; }
function balanceDetail(balance: Record<string, string>): string { return balance.key ? (balance.currency || "") : `充值 ${balance.topped_up_balance || "—"} · 赠金 ${balance.granted_balance || "—"}`; }
function openConnection() { Object.assign(form, { legal_entity_id: entities.value[0]?.id ?? "", service_instance_id: "", name: isDeepSeek.value ? "DeepSeek 开放平台账户" : isMiniMax.value ? "MiniMax Token Plan 订阅" : "阿里云财务账户", api_key: "", access_key_id: "", access_key_secret: "" }); modal.value = true; }
async function load() { loading.value = true; try { const [connectionRows, entityRows, instanceRows] = await Promise.all([api.usageConnections(), api.legalEntities(), api.serviceInstances()]); connections.value = connectionRows; entities.value = entityRows; instances.value = instanceRows; } catch (reason) { error.value = reason instanceof Error ? reason.message : "加载失败"; } finally { loading.value = false; } }
async function save() { saving.value = true; error.value = ""; try { await api.createUsageConnection({ platform_code: platformCode.value, legal_entity_id: form.legal_entity_id, service_instance_id: form.service_instance_id || null, name: form.name, api_key: isAliyun.value ? null : form.api_key, access_key_id: isAliyun.value ? form.access_key_id : null, access_key_secret: isAliyun.value ? form.access_key_secret : null, key_type: isMiniMax.value ? "token_plan" : null }); modal.value = false; notice.value = "连接已保存；点击测试或同步读取平台当前状态。"; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "保存失败"; } finally { saving.value = false; } }
async function test(item: UsageConnection) { workingId.value = item.id; error.value = ""; try { const result = await api.testUsageConnection(item.id); if (result.snapshot) item.configuration.latest_snapshot = result.snapshot; notice.value = result.message; } catch (reason) { error.value = reason instanceof Error ? reason.message : "测试失败"; } finally { workingId.value = ""; } }
async function sync(item: UsageConnection) { workingId.value = item.id; error.value = ""; try { notice.value = (await api.syncUsageConnection(item.id)).message; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "同步失败"; } finally { workingId.value = ""; } }
onMounted(load);
</script>

<template>
  <div class="page-stack">
    <PageHeader :title="platformMeta.title" :description="platformMeta.description"><RouterLink to="/services" class="secondary-button"><ArrowLeft :size="16" />返回平台列表</RouterLink><button class="primary-button" @click="openConnection"><Plus :size="17" />{{ platformMeta.connect }}</button></PageHeader>
    <div v-if="error" class="message-panel error-message">{{ error }}</div><div v-if="notice" class="message-panel">{{ notice }}</div>
    <section class="content-panel platform-capability"><div class="panel-heading"><div><h2>接口能力边界</h2><p v-if="isDeepSeek">可读：账号当前总余额、赠金余额、充值余额。不可读：按 API Key 历史用量、按 API Key 剩余额度。</p><p v-else-if="isMiniMax">可读：Token Plan 订阅 Key 所属套餐的可用额度、积分和用量状态。不可读：普通按量 API Key 的账户余额或历史用量。</p><p v-else>可读：账户可用额度、现金余额、信控余额。凭证需为具有 BSS 只读财务权限的 RAM AccessKey；不读取单次 API 调用级消费明细。</p></div><button class="icon-button" :disabled="loading" @click="load"><RefreshCw :size="17" /></button></div></section>
    <section class="content-panel"><div class="panel-heading"><div><h2>{{ isMiniMax ? '订阅连接与当前额度' : '账户连接与当前余额' }}</h2><p>{{ isDeepSeek ? '每条连接代表一个开放平台账号，不代表一把 API Key 的独立余额。' : isMiniMax ? '每条连接代表一个 Token Plan 订阅身份，不等同于普通按量 API Key。' : '每条连接代表一个阿里云财务账户，不代表单个 AccessKey 的独立余额。' }}</p></div></div><div class="connection-detail-list"><article v-for="item in platformConnections" :key="item.id"><header><div><strong>{{ item.name }}</strong><span>{{ isAliyun ? config(item, 'access_key_id_masked') : config(item, 'api_key_masked') }} · {{ entityName[item.legal_entity_id] || '公司主体' }}</span><small>{{ item.service_instance_id ? `关联：${instanceName[item.service_instance_id]}` : '未关联服务实例；仍可同步平台账户状态' }}</small></div><StatusBadge :tone="item.status === 'enabled' ? 'success' : 'default'">{{ item.status === 'enabled' ? '已启用' : '已停用' }}</StatusBadge></header><div class="snapshot-grid" v-if="!isMiniMax && balances(item).length"><div v-for="balance in balances(item)" :key="balance.key || balance.currency"><span>{{ balanceLabel(balance) }}</span><strong>{{ balanceValue(balance) }}</strong><small>{{ balanceDetail(balance) }}</small></div></div><div class="snapshot-grid" v-else-if="isMiniMax && miniMaxItems(item).length"><div v-for="quota in miniMaxItems(item)" :key="quota.label"><span>{{ quota.label }}</span><strong>{{ quota.remaining }}</strong><small>以 MiniMax 接口返回字段为准</small></div></div><div v-else class="mini-empty">尚未读取当前{{ isMiniMax ? '套餐额度' : '账户余额' }}。保存凭证后点击“测试”或“同步”。</div><footer><span>{{ item.last_synced_at ? `上次同步：${new Date(item.last_synced_at).toLocaleString('zh-CN')}` : '尚未同步' }}</span><div><button class="secondary-button" :disabled="workingId === item.id" @click="test(item)">测试凭证</button><button class="primary-button" :disabled="workingId === item.id || item.status !== 'enabled'" @click="sync(item)"><Play :size="15" />同步当前状态</button></div></footer></article><div v-if="!platformConnections.length && !loading" class="large-empty-panel"><component :is="isMiniMax ? Gauge : CircleDollarSign" :size="28" /><strong>尚未连接 {{ platformMeta.title }}</strong><p>{{ isAliyun ? '保存具备 BSS 只读财务权限的 RAM AccessKey 后，即可读取该账号当前余额。' : isMiniMax ? '保存 Token Plan 订阅 Key 后，即可读取套餐、额度和积分状态。' : '保存一个有账户访问权限的 Bearer API Key 后，即可读取该账号当前余额。' }}</p><button class="primary-button" @click="openConnection"><Plus :size="16" />{{ platformMeta.connect }}</button></div></div></section>
    <ModalPanel v-if="modal" :title="platformMeta.connect" @close="modal = false"><form class="form-grid one-column" @submit.prevent="save"><div class="form-hint"><template v-if="isAliyun">连接器仅调用阿里云 BSS OpenAPI 的账户余额查询。请使用最小权限的 RAM AccessKey，并授予 QueryAccountBalance 的只读权限。</template><template v-else-if="isMiniMax">仅接受 Token Plan 订阅 Key。普通按量 API Key 与订阅 Key 不通用，且官方公开文档没有提供其余额或历史用量查询接口。</template><template v-else>该凭证只用于调用官方余额接口。它读取的是账号总余额，系统不会将它登记为可按 Key 分析的用量记录。</template></div><label><span>归属公司 *</span><select v-model="form.legal_entity_id" required><option value="" disabled>选择公司</option><option v-for="item in entities" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>连接名称 *</span><input v-model="form.name" required /></label><template v-if="isAliyun"><label><span>RAM AccessKey ID *</span><input v-model="form.access_key_id" required autocomplete="off" placeholder="保存后只显示脱敏标识" /></label><label><span>RAM AccessKey Secret *</span><input v-model="form.access_key_secret" type="password" required autocomplete="off" placeholder="仅用于阿里云签名请求" /></label></template><label v-else><span>{{ platformMeta.credential }} *</span><input v-model="form.api_key" type="password" required autocomplete="off" placeholder="保存后只显示脱敏标识" /></label><label><span>关联服务实例</span><select v-model="form.service_instance_id"><option value="">不关联（只看平台账户状态）</option><option v-for="item in instances" :key="item.id" :value="item.id">{{ instanceName[item.id] }}</option></select></label><div class="form-actions"><button type="button" class="secondary-button" @click="modal = false">取消</button><button class="primary-button" :disabled="saving">{{ saving ? '保存中…' : '保存连接' }}</button></div></form></ModalPanel>
  </div>
</template>
