<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { BellRing, CalendarClock, Plus, RefreshCw } from "lucide-vue-next";
import ModalPanel from "../components/ModalPanel.vue";
import PageHeader from "../components/PageHeader.vue";
import StatusBadge from "../components/StatusBadge.vue";
import { api, type Person, type UsageAlertRule, type UsageMonitoringOverview, type UsageNotificationLog, type UsageNotificationSchedule } from "../lib/api";

const overview = ref<UsageMonitoringOverview>({ connections: [], dingtalk_recipient_person_ids: [] }); const people = ref<Person[]>([]); const rules = ref<UsageAlertRule[]>([]); const schedules = ref<UsageNotificationSchedule[]>([]); const logs = ref<UsageNotificationLog[]>([]); const loading = ref(true); const error = ref(""); const notice = ref(""); const modal = ref<"rule" | "schedule" | "">(""); const saving = ref(false);
const ruleForm = reactive({ provider_connection_id: "", name: "", metric_key: "balance", threshold: "", recipient_person_ids: [] as string[] });
const scheduleForm = reactive({ name: "", connection_ids: [] as string[], recipient_person_ids: [] as string[], time_of_day: "09:00" });
const recipientPeople = computed(() => people.value.filter((person) => overview.value.dingtalk_recipient_person_ids.includes(person.id)));
const connectionName = computed(() => Object.fromEntries(overview.value.connections.map((item) => [item.id, `${item.name} · ${item.platform_code}`])));
const personName = computed(() => Object.fromEntries(people.value.map((item) => [item.id, item.display_name])));
function selectedValues(event: Event): string[] { return Array.from((event.target as HTMLSelectElement).selectedOptions).map((item) => item.value); }
function openRule() { Object.assign(ruleForm, { provider_connection_id: overview.value.connections[0]?.id ?? "", name: "余额/额度低于阈值告警", metric_key: "balance", threshold: "", recipient_person_ids: recipientPeople.value.slice(0, 1).map((item) => item.id) }); modal.value = "rule"; }
function openSchedule() { Object.assign(scheduleForm, { name: "每日平台余额与额度汇总", connection_ids: overview.value.connections.map((item) => item.id), recipient_person_ids: recipientPeople.value.slice(0, 1).map((item) => item.id), time_of_day: "09:00" }); modal.value = "schedule"; }
function adjustMetric() { const connection = overview.value.connections.find((item) => item.id === ruleForm.provider_connection_id); ruleForm.metric_key = connection?.platform_code === "minimax" ? "quota_remaining" : "balance"; }
async function load() { loading.value = true; try { const [o, p, r, s, l] = await Promise.all([api.usageMonitoringOverview(), api.people(), api.usageAlertRules(), api.usageNotificationSchedules(), api.usageNotificationLogs()]); overview.value = o; people.value = p; rules.value = r; schedules.value = s; logs.value = l; } catch (reason) { error.value = reason instanceof Error ? reason.message : "加载失败"; } finally { loading.value = false; } }
async function saveRule() { saving.value = true; try { await api.createUsageAlertRule({ ...ruleForm, recipient_person_ids: ruleForm.recipient_person_ids }); modal.value = ""; notice.value = "告警规则已保存；平台同步后会在首次低于阈值时发送钉钉工作通知。"; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "保存失败"; } finally { saving.value = false; } }
async function saveSchedule() { saving.value = true; try { await api.createUsageNotificationSchedule({ ...scheduleForm, recipient_person_ids: scheduleForm.recipient_person_ids, connection_ids: scheduleForm.connection_ids, timezone: "Asia/Shanghai" }); modal.value = ""; notice.value = "定时发送规则已保存。"; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "保存失败"; } finally { saving.value = false; } }
async function runNow() { try { const result = await api.runUsageMonitoring(); notice.value = `监控已执行：同步 ${result.synced || 0} 个连接，发送告警 ${result.alerts_sent || 0} 条。`; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : "执行失败"; } }
onMounted(load);
</script>
<template>
  <div class="page-stack"><PageHeader title="额度告警与定时通知" description="依据各平台已公开且已接入的接口数据进行告警；通过现有钉钉内部应用发送工作通知。"><button class="secondary-button" :disabled="loading" @click="load"><RefreshCw :size="16" />刷新</button><button class="primary-button" @click="runNow"><BellRing :size="16" />立即执行监控</button></PageHeader>
    <div v-if="error" class="message-panel error-message">{{ error }}</div><div v-if="notice" class="message-panel">{{ notice }}</div>
    <section class="content-panel"><div class="panel-heading"><div><h2>告警规则</h2><p>当前余额或最低剩余额度首次低于阈值时，向已绑定钉钉身份的收件人发送通知。</p></div><button class="primary-button" :disabled="!recipientPeople.length || !overview.connections.length" @click="openRule"><Plus :size="16" />新增告警</button></div><div class="connection-detail-list"><article v-for="rule in rules" :key="rule.id"><header><div><strong>{{ rule.name }}</strong><span>{{ connectionName[rule.provider_connection_id] || '平台连接' }} · {{ rule.metric_key }} &lt; {{ rule.threshold }}</span><small>收件人：{{ rule.recipient_person_ids.map((id) => personName[id] || '未识别人员').join('、') || '未设置' }}</small></div><StatusBadge :tone="rule.last_state === 'breached' ? 'warning' : rule.enabled ? 'success' : 'default'">{{ rule.last_state === 'breached' ? '已触发' : rule.enabled ? '已启用' : '已停用' }}</StatusBadge></header><footer><span>{{ rule.last_notified_at ? `最近通知：${new Date(rule.last_notified_at).toLocaleString('zh-CN')}` : '尚未触发通知' }}</span></footer></article><div v-if="!rules.length && !loading" class="mini-empty">还没有告警规则。先建立平台连接并同步数据。</div></div></section>
    <section class="content-panel"><div class="panel-heading"><div><h2>定时发送</h2><p>每天在指定时间发送已接入平台的最近一次余额和额度快照；不会伪造平台未公开的数据。</p></div><button class="primary-button" :disabled="!recipientPeople.length || !overview.connections.length" @click="openSchedule"><CalendarClock :size="16" />新增定时发送</button></div><div class="connection-detail-list"><article v-for="item in schedules" :key="item.id"><header><div><strong>{{ item.name }}</strong><span>每日 {{ item.time_of_day }}（{{ item.timezone }}）</span><small>{{ item.connection_ids.map((id) => connectionName[id] || '已删除连接').join('、') }}</small></div><StatusBadge :tone="item.enabled ? 'success' : 'default'">{{ item.enabled ? '已启用' : '已停用' }}</StatusBadge></header><footer><span>{{ item.last_sent_on ? `最近发送：${item.last_sent_on}` : '尚未发送' }}</span></footer></article><div v-if="!schedules.length && !loading" class="mini-empty">还没有定时发送规则。</div></div></section>
    <section class="content-panel"><div class="panel-heading"><div><h2>发送记录</h2><p>保留最近 100 条告警与定时发送结果。</p></div></div><div class="connection-detail-list compact"><article v-for="log in logs.slice(0, 10)" :key="log.id"><header><div><strong>{{ log.message_summary }}</strong><small>{{ new Date(log.created_at).toLocaleString('zh-CN') }} · {{ log.recipient_count }} 位收件人</small></div><StatusBadge :tone="log.status === 'sent' ? 'success' : 'warning'">{{ log.status }}</StatusBadge></header></article><div v-if="!logs.length" class="mini-empty">尚无发送记录。</div></div></section>
    <ModalPanel v-if="modal === 'rule'" title="新增额度告警" @close="modal = ''"><form class="form-grid one-column" @submit.prevent="saveRule"><label><span>平台连接 *</span><select v-model="ruleForm.provider_connection_id" required @change="adjustMetric"><option v-for="item in overview.connections" :key="item.id" :value="item.id">{{ item.name }} · {{ item.platform_code }}</option></select></label><label><span>规则名称 *</span><input v-model="ruleForm.name" required /></label><label><span>告警阈值 *</span><input v-model="ruleForm.threshold" type="number" min="0" step="any" required /></label><label><span>钉钉收件人 *</span><select multiple :value="ruleForm.recipient_person_ids" required @change="ruleForm.recipient_person_ids = selectedValues($event)"><option v-for="person in recipientPeople" :key="person.id" :value="person.id">{{ person.display_name }}</option></select><small>仅显示已同步并绑定钉钉身份的人员。</small></label><div class="form-actions"><button type="button" class="secondary-button" @click="modal = ''">取消</button><button class="primary-button" :disabled="saving">保存规则</button></div></form></ModalPanel>
    <ModalPanel v-if="modal === 'schedule'" title="新增定时发送" @close="modal = ''"><form class="form-grid one-column" @submit.prevent="saveSchedule"><label><span>名称 *</span><input v-model="scheduleForm.name" required /></label><label><span>每天发送时间 *</span><input v-model="scheduleForm.time_of_day" type="time" required /></label><label><span>汇总平台连接 *</span><select multiple :value="scheduleForm.connection_ids" required @change="scheduleForm.connection_ids = selectedValues($event)"><option v-for="item in overview.connections" :key="item.id" :value="item.id">{{ item.name }} · {{ item.platform_code }}</option></select></label><label><span>钉钉收件人 *</span><select multiple :value="scheduleForm.recipient_person_ids" required @change="scheduleForm.recipient_person_ids = selectedValues($event)"><option v-for="person in recipientPeople" :key="person.id" :value="person.id">{{ person.display_name }}</option></select></label><div class="form-actions"><button type="button" class="secondary-button" @click="modal = ''">取消</button><button class="primary-button" :disabled="saving">保存定时发送</button></div></form></ModalPanel>
  </div>
</template>
